make script usable with tcsh

diff --git a/netsoul b/netsoul
--- a/netsoul
+++ b/netsoul
@@ -6,18 +6,18 @@
 # Written By: Alpha14 (contact@alpha14.com)
 # (3-2015)
 
-version=6
+version=7
 remote_ip="google.fr"
 ns_server="ns-server.epitech.net"
-# ns_auth location
-ns_auth="ns_auth"
+ns_auth="ns_auth" # ns_auth location
+#interval variables
 msg=0
 verbose='false'
 user=''
 tries=0
 
-command -v $ns_auth >/dev/null 2>&1 ||
-{ echo "ns_auth not Found. Aborting." >&2; exit 1; }
+command -v $ns_auth 2>&1 >/dev/null ||
+{ echo "ns_auth not Found. Aborting."; exit 1; }
 
 # Arguments
 while getopts 'u:v' flag; do
@@ -30,7 +30,7 @@ done
 
 xping()
 {
-    ping -q -c 2 -W 1 $1 &> /dev/null
+    ping -q -c 2 -W 1 "$1" 2>&1 >/dev/null
 }
 
 control_c()
@@ -104,9 +104,9 @@ ns_connect()
 
     if [ -n "$user" ]
     then
-	$ns_auth -u $user &> /dev/null
+	$ns_auth -u $user 2>&1 >/dev/null
     else
-	$ns_auth &> /dev/null
+	$ns_auth 2>&1 >/dev/null
     fi
 
     sleep 4
@@ -143,7 +143,7 @@ print()
 	then
 	    echo "[Netsoul] $1"
 	fi
-	notify-send 'Netsoul' "$1" --icon=dialog-information -t 2000
+	command -v notify-send  2>&1 >/dev/null && notify-send 'Netsoul' "$1" --icon=dialog-information -t 2000  2>&1 >/dev/null
     fi
     msg=$1
 }
